### ISSUE TITLE
Documentation or sample request: How to continue receiving on channel until it closes

### ISSUE THREAD

**Issue by ryanwalls** [uber-go/cadence-client#390] opened 2018-02-01 12:07 UTC
I'm trying to receive on a signal channel continuously the whole time my workflow is running.  Would be great if the documentation or samples included an example that received on a channel until it was closed.  Looked through https://github.com/samarabbas/cadence-samples and https://github.com/uber-go/cadence-client/blob/master/internal/internal_coroutines_test.go and couldn't find an explicit example.

Would this be the best approach?
```
       	workflow.Go(ctx, func(ctx workflow.Context) {
		percentCompleteChan := workflow.GetSignalChannel(ctx, activities.PercentCompleteChannel)
		more := true
		for more {
			var signal activities.PercentCompleteSignal
			more = percentCompleteChan.Receive(ctx, &signal)
			ao := workflow.ActivityOptions{
				ScheduleToStartTimeout: 1 * time.Minute,
				StartToCloseTimeout:    1 * time.Minute,
				ScheduleToCloseTimeout: 1 * time.Minute,
				HeartbeatTimeout:       1 * time.Minute,
			}
			workflow.ExecuteActivity(workflow.WithActivityOptions(ctx, ao), activities.UpdatePercentComplete, keys.SimulationManager, simulationID, signal.ActivityID, signal.PercentComplete).Get(ctx, nil)
		}
	})
```

Also, I can't get a test to pass asserting that the signal was processed.  It always says the `UpdatePercentComplete` activity is never called.  Any ideas? 

My test:
```
t.Run("WhenPercentCompleteSignalReceivedExpectsWorkflowToCallUpdatePercentCompleteActivity", func(t *testing.T) {
		// arrange
		env := s.NewTestWorkflowEnvironment()
		env.OnActivity(activities.CreateSimulationActivities, mock.Anything, keys.SimulationManager, mock.Anything).Return(nil)
		env.OnActivity(activities.RunVoxelization, mock.Anything, simulationID).Return(&activities.RunVoxelizationOutput{}, nil)
		env.OnActivity(activities.RunMechanicsSolver, mock.Anything, simulationID, "").Return(nil, nil)
		env.OnWorkflow(postprocessing.Workflow, mock.Anything, simulationID, "", "", "", "").Return(&postprocessing.WorkflowOutputs{}, nil)
		env.OnActivity(activities.CompleteEntity, mock.Anything, keys.SimulationManager, simulationID, orgID, "").Return(nil)
		activityID := "activity id"
		signal := &activities.PercentCompleteSignal{ActivityID: activityID, PercentComplete: 10}
		env.OnActivity(activities.UpdatePercentComplete, mock.Anything, keys.SimulationManager, simulationID, activityID, signal.PercentComplete).Return(nil)

		// act
		env.RegisterDelayedCallback(func() {
			env.SignalWorkflow(activities.PercentCompleteChannel, signal)
		}, time.Second)
		env.ExecuteWorkflow(Workflow, simulationID, orgID, false, false)

		// assert
		assert.True(t, env.IsWorkflowCompleted(), "Expected workflow to complete")
		assert.NoError(t, env.GetWorkflowError(), "Expected workflow to not return an error")
		env.AssertExpectations(t)
	})
```

**Comment by mfateev** [comment] 2018-02-01 14:54
The code snippet looks OK to me. But it doesn't contain any logic to notify the other parts of the workflow that the signal receiving goroutine is done. Could it be that the main workflow function returns (closing the workflow) before any signal is received?

**Comment by ryanwalls** [comment] 2018-02-01 17:35
@mfateev Yeah, that's what is happening.  What paradigm do you recommend for that?  The signal receiving goroutine needs to run until the workflow exits.  So I'm closing the channel right at the end of the workflow.  

But since the test is using `RegisterDelayedCallback` it doesn't get executed before the channel closes.  The hack I'm using right now to get the test to pass is this:

```
	workflow.Sleep(ctx, 2*time.Second)
	percentCompleteChan.Close()
```

Any better ideas?

**Comment by mfateev** [comment] 2018-02-01 18:20
I see. The problem is that mocked activities by default return immediately. You can give them some latency using mock `After` function:

```
env.OnActivity(activities.CreateSimulationActivities, 
      mock.Anything, keys.SimulationManager, mock.Anything).
           Return(nil).After(10 * time.Minute)
```
I think we want by default give mocked activities some latency. Something like timeout time divided by 2.

**Comment by ryanwalls** [comment] 2018-02-01 18:24
@mfateev Thanks!  Will give this a shot.

For this issue, I'll leave it open until I have time to add an example via PR.

**Closed** 2024-11-07 21:24 UTC
Labels: documentation
