### ISSUE TITLE
Running an activity in isolation for a unit test, getting "unsupported respond type <nil>" error

### ISSUE THREAD

**Issue by ryanwalls** [uber-go/cadence-client#297] opened 2017-12-01 19:50 UTC
Trying to write a simple unit test for executing an activity in isolation.  Have several tests working for running a whole workflow, but I can't get this one to work.    

Here's my simplified activity:
```
func RunVoxelization(ctx context.Context, simulationID int) (*RunVoxelizationOutput, error) {
	logger.Log.Debug("In RunVoxelization!")
	return nil, cadence.ErrActivityResultPending
}
```

Here's my test: 
```
func TestRunVoxelization(t *testing.T) {
	// arrange
	s := &cadence.WorkflowTestSuite{}
	env := s.NewTestActivityEnvironment()
	simulationID := 10

	// act
	_, err := env.ExecuteActivity(RunVoxelization, simulationID)

	// assert
	assert.Equal(t, cadence.ErrActivityResultPending, err, "Expected ErrActivityResultPending error returned")
}
```

Here's my result:
```
--- FAIL: TestRunVoxelization (0.00s)
	assertions.go:239: 
                          
	Error Trace:	voxelization_test.go:44
		
	Error:      	Not equal: 
		
	            	expected: &errors.errorString{s:"not error: do not autocomplete, using Client.CompleteActivity() to complete"}
		
	            	actual: &errors.errorString{s:"unsupported respond type <nil>"}
		
	            	
		
	            	Diff:
		
	            	--- Expected
		
	            	+++ Actual
		
	            	@@ -1,2 +1,2 @@
		
	            	-(*errors.errorString)(not error: do not autocomplete, using Client.CompleteActivity() to complete)
		
	            	+(*errors.errorString)(unsupported respond type <nil>)
		
	            	 
		
	Messages:   	Expected ErrActivityResultPending error returned
```

Any ideas?

I saw a very similar test here: https://github.com/uber-go/cadence-client/blob/84eab8ac1241993da3b297b5587020ba46b2c919/internal_workflow_testsuite_test.go#L291-L314, so not sure why mine doesn't work.

**Comment by mfateev** [comment] 2017-12-01 20:39
It is by design :).

ErrActivityResultPending is returned from activity's implementation to indicate the activity is not completed when nactivity method returns. Activity needs to be completed by Client.CompleteActivity() separately. For example, if an activity require human interaction (like approve an expense report), the activity could return ErrActivityResultPending which indicate the activity is not done yet. Then, when the waited human action happened, it needs to trigger something that could report the activity completed event to cadence server via Client.CompleteActivity() API.

So when this error is returned ExecuteActivity is still blocked waiting for that CompleteActivity call. Use env.CompleteActivity to complete it asynchronously in the unit test scenario. Here is the relevant unit test: https://github.com/uber-go/cadence-client/blob/84eab8ac1241993da3b297b5587020ba46b2c919/internal_workflow_testsuite_test.go#L316

**Comment by mfateev** [comment] 2017-12-01 21:02
I've got confused. I thought that you are using Workflow testing environment. But as you are unit testing individual activity your unit test is correct. Apparently our unit testing framework incorrectly interprets the  ErrActivityResultPending in this particular case.

**Comment by ryanwalls** [comment] 2017-12-01 21:20
@mfateev Ok, thanks for your help.  Yep, looks like if I return a regular error instead of `ErrActivityResultPending` it handles it okay.

**Comment by mfateev** [comment] 2017-12-02 20:30
Yes, because ErrActivityResultPending has special meaning. But we are fixing this particular test method to pass it through to enable unit testing async activities.

**Comment by mfateev** [comment] 2017-12-06 02:17
Fixed in https://github.com/uber-go/cadence-client/pull/299
Resolving.

**Closed by mfateev** 2017-12-06 02:17 UTC
