### ISSUE TITLE
panic: invalid state transition

### ISSUE THREAD

**Issue by vvelikodny** [uber-go/cadence-client#290] opened 2017-11-27 19:39 UTC
I try to run my test workflow and got cadence worker logs:

```
2017-11-27T19:04:14.050Z	INFO	common/sample_helper.go:130	Cadence worker started.
2017-11-27T19:06:00.077Z	INFO	workflow/workflow.go:34	Run RankingWorkflow	{"Domain": "samples-domain", "TaskList": "ranking", "WorkerID": "1@30323ab1b2f4@ranking", "WorkflowType": "gitlab.com/-/workers/cmd/ranking/workflow.RankingWorkflow", "WorkflowID": "ranking_c97b70c4-6fcd-404e-8adb-343845a8203f", "RunID": "0aa57e44-dc30-41c2-9225-afb133e4a9fd", "groupId": 1}
2017-11-27T19:06:00.078Z	DEBUG	cadence/internal_event_handlers.go:297	ExecuteActivity	{"Domain": "samples-domain", "TaskList": "ranking", "WorkerID": "1@30323ab1b2f4@ranking", "WorkflowType": "gitlab.com/-/workers/cmd/ranking/workflow.RankingWorkflow", "WorkflowID": "ranking_c97b70c4-6fcd-404e-8adb-343845a8203f", "RunID": "0aa57e44-dc30-41c2-9225-afb133e4a9fd", "ActivityID": "0", "ActivityType": "gitlab.com/-/workers/cmd/ranking/workflow.GetKeywordGroupActivity"}
2017/11/27 19:06:00 Group to process: {Id:1 SearchEngineId:1 Status:pending Keywords:google Avg:0xc4200139e8 Country:com City: Lang:en Domain:google.com}
2017-11-27T19:06:00.184Z	WARN	cadence/internal_task_handlers.go:476	Cached sticky workflow state is missing some events.	{"Domain": "samples-domain", "TaskList": "ranking", "WorkerID": "1@30323ab1b2f4@ranking", "CachedPreviousStartedEventID": 3, "TaskFirstEventID": 1, "TaskStartedEventID": 9, "TaskPreviousStartedEventID": 3}
gitlab.com/-/workers/vendor/go.uber.org/cadence.(*workflowTaskHandlerImpl).getOrCreateWorkflowContext
	/Users//Dev/go/src/gitlab.com//workers/vendor/go.uber.org/cadence/internal_task_handlers.go:476
gitlab.com//workers/vendor/go.uber.org/cadence.(*workflowTaskHandlerImpl).ProcessWorkflowTask
	/Users//Dev/go/src/gitlab.com//workers/vendor/go.uber.org/cadence/internal_task_handlers.go:544
gitlab.com//workers/vendor/go.uber.org/cadence.(*workflowTaskPoller).ProcessTask
	/Users//Dev/go/src/gitlab.com//workers/vendor/go.uber.org/cadence/internal_task_pollers.go:180
gitlab.com//workers/vendor/go.uber.org/cadence.(*baseWorker).processTask
	/Users//Dev/go/src/gitlab.com//workers/vendor/go.uber.org/cadence/internal_worker_base.go:249
2017-11-27T19:06:00.191Z	INFO	workflow/workflow.go:49	KEYWORDS: 	{"Domain": "samples-domain", "TaskList": "ranking", "WorkerID": "1@30323ab1b2f4@ranking", "WorkflowType": "gitlab.com/-/workers/cmd/ranking/workflow.RankingWorkflow", "WorkflowID": "ranking_c97b70c4-6fcd-404e-8adb-343845a8203f", "RunID": "0aa57e44-dc30-41c2-9225-afb133e4a9fd", "keywords": "google/n/tyandex"}
2017-11-27T19:06:00.191Z	INFO	workflow/workflow.go:60	Run KeywordStatActivity with word: 	{"Domain": "samples-domain", "TaskList": "ranking", "WorkerID": "1@30323ab1b2f4@ranking", "WorkflowType": "gitlab.com/-/workers/cmd/ranking/workflow.RankingWorkflow", "WorkflowID": "ranking_c97b70c4-6fcd-404e-8adb-343845a8203f", "RunID": "0aa57e44-dc30-41c2-9225-afb133e4a9fd", "k": "google"}
2017-11-27T19:06:00.191Z	INFO	workflow/workflow.go:60	Run KeywordStatActivity with word: 	{"Domain": "samples-domain", "TaskList": "ranking", "WorkerID": "1@30323ab1b2f4@ranking", "WorkflowType": "gitlab.com/-/workers/cmd/ranking/workflow.RankingWorkflow", "WorkflowID": "ranking_c97b70c4-6fcd-404e-8adb-343845a8203f", "RunID": "0aa57e44-dc30-41c2-9225-afb133e4a9fd", "k": "yandex"}
2017-11-27T19:06:00.191Z	DEBUG	cadence/internal_event_handlers.go:297	ExecuteActivity	{"Domain": "samples-domain", "TaskList": "ranking", "WorkerID": "1@30323ab1b2f4@ranking", "WorkflowType": "gitlab.com/-/workers/cmd/ranking/workflow.RankingWorkflow", "WorkflowID": "ranking_c97b70c4-6fcd-404e-8adb-343845a8203f", "RunID": "0aa57e44-dc30-41c2-9225-afb133e4a9fd", "ActivityID": "1", "ActivityType": "gitlab.com/-/workers/cmd/ranking/workflow.GetKeywordStatActivity"}
2017-11-27T19:06:00.191Z	DEBUG	cadence/internal_event_handlers.go:297	ExecuteActivity	{"Domain": "samples-domain", "TaskList": "ranking", "WorkerID": "1@30323ab1b2f4@ranking", "WorkflowType": "gitlab.com/-/workers/cmd/ranking/workflow.RankingWorkflow", "WorkflowID": "ranking_c97b70c4-6fcd-404e-8adb-343845a8203f", "RunID": "0aa57e44-dc30-41c2-9225-afb133e4a9fd", "ActivityID": "2", "ActivityType": "gitlab.com/-/workers/cmd/ranking/workflow.GetKeywordStatActivity"}
panic: invalid state transition: attempt to handleInitiatedEvent, DecisionType: Activity, ID: 0, state=Completed, isDone()=true, history=[Created handleDecisionSent DecisionSent handleInitiatedEvent Initiated handleCompletionEvent Completed]

goroutine 209 [running]:
gitlab.com//workers/vendor/go.uber.org/cadence.(*decisionStateMachineBase).failStateTransition(0xc420446c80, 0xbde72a, 0x14)
	/Users//Dev/go/src/gitlab.com//workers/vendor/go.uber.org/cadence/internal_decision_state_machine.go:282 +0x124
gitlab.com/-/workers/vendor/go.uber.org/cadence.(*decisionStateMachineBase).handleInitiatedEvent(0xc420446c80)
	/Users/-/Dev/go/src/gitlab.com/-/workers/vendor/go.uber.org/cadence/internal_decision_state_machine.go:314 +0x424
gitlab.com/-/workers/vendor/go.uber.org/cadence.(*decisionsHelper).handleActivityTaskScheduled(0xc420450e10, 0x5, 0xc4205fbbd8, 0x1)
	/Users/-/Dev/go/src/gitlab.com/-/workers/vendor/go.uber.org/cadence/internal_decision_state_machine.go:643 +0xa7
gitlab.com/-/workers/vendor/go.uber.org/cadence.(*workflowExecutionEventHandlerImpl).ProcessEvent(0xc420350b00, 0xc4204fa420, 0x1, 0x0, 0x0, 0xc42000c238, 0x0, 0x1)
	/Users/-/Dev/go/src/gitlab.com/-/workers/vendor/go.uber.org/cadence/internal_event_handlers.go:470 +0x568
gitlab.com/-/workers/vendor/go.uber.org/cadence.(*workflowTaskHandlerImpl).ProcessWorkflowTask(0xc4203965a0, 0xc42045d5e0, 0xf66be0, 0xc420338cc0, 0xed1ae5900, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/-/Dev/go/src/gitlab.com/-/workers/vendor/go.uber.org/cadence/internal_task_handlers.go:603 +0x782
gitlab.com/-/workers/vendor/go.uber.org/cadence.(*workflowTaskPoller).ProcessTask(0xc420384d20, 0xa90800, 0xc4205adbf0, 0x2, 0xffffffffffffffff)
	/Users/-/Dev/go/src/gitlab.com/-/workers/vendor/go.uber.org/cadence/internal_task_pollers.go:180 +0xbc
gitlab.com/-/workers/vendor/go.uber.org/cadence.(*baseWorker).processTask(0xc4200ea540, 0xa90800, 0xc4205adbf0)
	/Users/-/Dev/go/src/gitlab.com/-/workers/vendor/go.uber.org/cadence/internal_worker_base.go:249 +0x66
created by gitlab.com/-/workers/vendor/go.uber.org/cadence.(*baseWorker).runTaskDispatcher
	/Users/-/Dev/go/src/gitlab.com/-/workers/vendor/go.uber.org/cadence/internal_worker_base.go:220 +0x1e9
```
The process of workflow like that:

- run `GetKeywordGroupActivity`
- then run `GetKeywordStatActivity` in parallel for the list of items, push results in cadence channel
- wait all results collected and push result to `SaveKeywordGroupStatActivity`

**Comment by mfateev** [comment] 2017-11-27 20:06
Are you getting this problem consistently or it was a one time failure?

**Comment by mfateev** [comment] 2017-11-27 20:38
This error might be caused by non deterministic workflow definition code. Would you check that you follow restrictions listed in Workflow section of the README?

**Comment by vvelikodny** [comment] 2017-11-27 20:58
@mfateev well, code worked, but then stop works and constantly panic with that error, I think because I move it to dockers, I've checked again and it seems works locally well, need to do more tests

**Comment by mfateev** [comment] 2017-11-27 21:10
My guess is that workflow code was changed while a workflow was open which counts like non deterministic behavior.

**Comment by vvelikodny** [comment] 2017-11-27 21:13
@mfateev yes, I saw it in README, please, could you clarify what mean `workflow was open`?

**Comment by mfateev** [comment] 2017-11-27 21:41
1. Workflow execution is started and makes some progress.
2. A worker with updated code is deployed.
3. A new worker tries to replay history produced by an old worker. As history doesn't match the new code the invalid state transition is raised.

The solution is to use cadence.GetVersion (https://github.com/uber-go/cadence-client/blob/297c8d46a2837125be9c92f843e34139498e9b45/workflow.go#L653) to update workflow code in deterministic manner.

**Comment by vvelikodny** [comment] 2017-11-27 22:42
> A new worker tries to replay history produced by an old worker. As history doesn't match the new code the invalid state transition is raised.
As I understand history saved in the Cassandra, but I tried to remove all containers and recreate everything, panic again

It seems something related versions compatibility of cadence 0.3.2 & latest cadence-client, b/c after I've built new `ubercadence/server` image from `master` branch, my code works again.

**Comment by mfateev** [comment] 2017-11-27 22:53
I see. There were pretty significant changes to both service and the client recently mostly related to sticky workflow execution. So it is not a surprise that the newest service version is needed for the client. BTW the sticky workflow execution is an ability to cache a workflow state on a client to not require a replay while it is cached.

**Comment by mfateev** [comment] 2017-11-28 22:39
I've filed https://github.com/uber/cadence/issues/435 to get client version validation on connection request. 
Resolving this issue.

**Closed by mfateev** 2017-11-28 22:39 UTC
