### ISSUE TITLE
Cadence buffered channel hangs not matching go's buffered channel behavior

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber-go/cadence-client#661] opened 2019-03-14 19:09 UTC
The following cadence code deadlocks
```
func Workflow(ctx workflow.Context) error {
	ch := workflow.NewBufferedChannel(ctx, 1)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var i int
		ch.Receive(ctx, &i)
		fmt.Printf("received value: %v\n", i)

	})
	for i := 0; i < 2; i++ {
		ch.Send(ctx, i)
		fmt.Printf("sent value: %v\n", i)
	}
	return nil
}
```

The following golang code does not
```
func main() {
	ch := make(chan int, 1)
	go func() {
		i := <-ch
		fmt.Printf("received value: %v\n", i)
	}()
	for i := 0; i < 2; i++ {
		ch<-i
		fmt.Printf("sent value: %v\n", i)
	}
}
```

**Comment by jquirke** [comment] 2019-03-15 23:58
Duplicate of https://github.com/uber-go/cadence-client/issues/661

**Comment by jquirke** [comment] 2019-03-16 00:00
https://github.com/uber-go/cadence-client/issues/666

**Comment by yycptt** [comment] 2019-03-18 16:59
Merged. Closing this issue.

**Closed by yycptt** 2019-03-18 16:59 UTC
