### ISSUE TITLE
go get fails with errors

### ISSUE THREAD

**Issue by mfateev** [uber-go/cadence-client#812] opened 2019-08-02 14:38 UTC
Customer reported:

_trying to get the cadence client via go get go.uber.org/cadence resulted in the following error. Error encountered:_

```
package go.uber.org/cadence        
    imports go.uber.org/cadence/.gen/go/cadence/workflowserviceclient: go.uber.org/cadence/.gen/go/cadence/workflowserviceclient: invalid import path: malformed 
    import path "go.uber.org/cadence/.gen/go/cadence/workflowserviceclient": leading dot in path elementpackage go.uber.org/cadence        
    imports go.uber.org/cadence/.gen/go/cadence/workflowservicetest: go.uber.org/cadence/.gen/go/cadence/workflowservicetest: invalid import path: malformed import path "go.uber.org/cadence/.gen/go/cadence/workflowservicetest": leading dot in path elementpackage go.uber.org/cadence       
    imports go.uber.org/cadence/.gen/go/shared: go.uber.org/cadence/.gen/go/shared: invalid import path: malformed import path "go.uber.org/cadence/.gen/go/shared": leading dot in path element
--
```
Did `go get `changed to validate paths?

**Comment by mfateev** [comment] 2019-08-05 05:03
I'm getting a different error. Should we even support "go get"? It doesn't deal with dependencies correctly.

```
clienttest: go get go.uber.org/cadence
# go.uber.org/cadence/internal/common
src/go.uber.org/cadence/internal/common/thrift_util.go:29:38: not enough arguments in call to thrift.NewTSerializer().Write
	have (thrift.TStruct)
	want (context.Context, thrift.TStruct)
src/go.uber.org/cadence/internal/common/thrift_util.go:51:27: not enough arguments in call to t.Protocol.Flush
	have ()
	want (context.Context)
src/go.uber.org/cadence/internal/common/thrift_util.go:55:28: not enough arguments in call to t.Transport.Flush
	have ()
	want (context.Context)
clienttest:
```

**Comment by pjediny** [comment] 2019-09-03 09:48
Why not add the go modules support to fix the issues with dependencies? The main cadence project already uses modules. And maybe move to newer thrift release, the 0.10.0 is from January 2017, but that would require more changes.

**Comment by sevein** [comment] 2019-09-06 14:34
@pjediny agree! Using Go modules, I've been able to import this client from my top-level module as long as I set the constraint myself. It'd be nice not having to do that. I've shared details here: https://github.com/uber-go/cadence-client/issues/523#issuecomment-528878431.

Perhaps this could be considered a duplicate of #812?

**Closed** 2019-09-28 02:01 UTC
Labels: bug

**Comment by Hayden-Chang** [comment] 2024-01-09 09:23
I use go 1.19 to resolve it.
